package lab1_tp4_colegio.Vistas;

import java.util.ArrayList;
import lab1_tp4_colegio.Alumno;
import lab1_tp4_colegio.Materia;

/**
 * @author G_10
 */
public class Frm_Colegio extends javax.swing.JFrame {

    private static ArrayList<Materia> lisMateria = new ArrayList();
    private static ArrayList<Alumno> lisAlum = new ArrayList();
    
    public Frm_Colegio() {
        initComponents();
    }
//get y set de listas Alumnos y Materias:
    public static ArrayList<Materia> getLisMateria() {
        return lisMateria;
    }

    public static ArrayList<Alumno> getLisAlum() {
        return lisAlum;
    }
            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio1 = new javax.swing.JDesktopPane();
        btn_imgFondo = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuOpciones = new javax.swing.JMenu();
        mnuAlumno = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuMateria = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        mnu_ins = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        escritorio1.setPreferredSize(new java.awt.Dimension(795, 550));

        btn_imgFondo.setBackground(new java.awt.Color(255, 255, 255));
        btn_imgFondo.setForeground(new java.awt.Color(255, 255, 255));
        btn_imgFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab1_tp4_colegio/Vistas/Recursos/Escudo uniG10-50porciento.png"))); // NOI18N
        btn_imgFondo.setBorderPainted(false);
        btn_imgFondo.setContentAreaFilled(false);
        btn_imgFondo.setFocusPainted(false);
        btn_imgFondo.setFocusable(false);

        escritorio1.setLayer(btn_imgFondo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorio1Layout = new javax.swing.GroupLayout(escritorio1);
        escritorio1.setLayout(escritorio1Layout);
        escritorio1Layout.setHorizontalGroup(
            escritorio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorio1Layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(btn_imgFondo)
                .addContainerGap(240, Short.MAX_VALUE))
        );
        escritorio1Layout.setVerticalGroup(
            escritorio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escritorio1Layout.createSequentialGroup()
                .addContainerGap(128, Short.MAX_VALUE)
                .addComponent(btn_imgFondo)
                .addGap(96, 96, 96))
        );

        mnuOpciones.setText("Carga");
        mnuOpciones.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        mnuOpciones.setPreferredSize(new java.awt.Dimension(150, 50));

        mnuAlumno.setText("Alumno");
        mnuAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAlumnoActionPerformed(evt);
            }
        });
        mnuOpciones.add(mnuAlumno);
        mnuOpciones.add(jSeparator1);

        mnuMateria.setText("Materias");
        mnuMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMateriaActionPerformed(evt);
            }
        });
        mnuOpciones.add(mnuMateria);

        jMenuBar1.add(mnuOpciones);

        jMenu11.setText("Gestion");
        jMenu11.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jMenu11.setPreferredSize(new java.awt.Dimension(150, 50));

        mnu_ins.setText("Inscripciones");
        mnu_ins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_insActionPerformed(evt);
            }
        });
        jMenu11.add(mnu_ins);

        jMenuBar1.add(jMenu11);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorio1, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAlumnoActionPerformed
        Fri_Alumno formalu=new Fri_Alumno();
        //escritorio1.removeAll();
        escritorio1.repaint();
        escritorio1.add(formalu);
        formalu.setVisible(true);
        escritorio1.moveToFront(formalu);

    }//GEN-LAST:event_mnuAlumnoActionPerformed

    private void mnu_insActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_insActionPerformed
        Fri_Inscripcion formIns=new Fri_Inscripcion();
        //escritorio1.removeAll();
        escritorio1.repaint();
        escritorio1.add(formIns);
        formIns.setVisible(true);
        escritorio1.moveToFront(formIns);
    }//GEN-LAST:event_mnu_insActionPerformed

    private void mnuMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMateriaActionPerformed
        Fri_Materia formMater=new Fri_Materia();
        //escritorio1.removeAll();
        escritorio1.repaint();
        escritorio1.add(formMater);
        formMater.setVisible(true);
        escritorio1.moveToFront(formMater);
    }//GEN-LAST:event_mnuMateriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Colegio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Colegio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Colegio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Colegio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Colegio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_imgFondo;
    private javax.swing.JDesktopPane escritorio1;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem mnuAlumno;
    private javax.swing.JMenuItem mnuMateria;
    private javax.swing.JMenu mnuOpciones;
    private javax.swing.JMenuItem mnu_ins;
    // End of variables declaration//GEN-END:variables
}
